# Generated by Django 5.1.1 on 2024-09-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kehadiran", "0002_kehadiran_is_present"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kehadiran",
            old_name="time_in",
            new_name="check_in_time",
        ),
        migrations.RenameField(
            model_name="kehadiran",
            old_name="time_out",
            new_name="check_out_time",
        ),
    ]
