# Generated by Django 5.1.1 on 2024-09-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kehadiran", "0003_rename_time_in_kehadiran_check_in_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kehadiran",
            name="status",
            field=models.CharField(
                choices=[("Telat", "Telat"), ("Tidak Telat", "Tidak Telat")],
                default="Tidak Telat",
                max_length=15,
            ),
        ),
    ]
