# Generated by Django 5.1.1 on 2024-09-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kehadiran", "0004_kehadiran_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kehadiran",
            name="status",
            field=models.CharField(
                choices=[
                    ("Telat", "Telat"),
                    ("Tidak Telat", "Tidak Telat"),
                    ("Izin", "Izin"),
                ],
                default="Tidak Telat",
                max_length=15,
            ),
        ),
    ]
