# Generated by Django 5.1.1 on 2024-09-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kehadiran", "0005_alter_kehadiran_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="kehadiran",
            name="alasan_izin",
            field=models.TextField(blank=True, null=True),
        ),
    ]
