# Generated by Django 5.1.1 on 2024-10-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kehadiran", "0006_kehadiran_alasan_izin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kehadiran",
            name="status",
            field=models.CharField(
                choices=[
                    ("Telat", "Telat"),
                    ("Tidak Telat", "Tidak Telat"),
                    ("Izin", "Izin"),
                    ("Izin Telat", "Izin Telat"),
                    ("Alpha", "Alpha"),
                ],
                default="Tidak Telat",
                max_length=15,
            ),
        ),
    ]
