# Generated by Django 5.1.1 on 2024-10-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kehadiran", "0008_announcement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Announcement",
        ),
    ]
