# Generated by Django 5.1.1 on 2024-10-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kehadiran", "0009_delete_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="kehadiran",
            name="announcement",
            field=models.TextField(blank=True, null=True),
        ),
    ]
