# Generated by Django 5.1.1 on 2024-09-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_karyawan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Karyawan', 'Karyawan')], max_length=50),
        ),
    ]
