# Generated by Django 5.1.1 on 2024-09-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Karyawan", "Karyawan")],
                default="Karyawan",
                max_length=50,
            ),
        ),
    ]
